---
- name: "1.3.1.1 | PATCH | Ensure SELinux is installed"
  when:
    - rule_1_3_1_1
    - not selinux_disable
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.3.1.1
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.package:
    name: libselinux
    state: present
