---

## Example file that maybe used for containers
## This is still dependant in the container usage
## Please confirm before running that it is suitable for your environment

section1: true
section2: true
section3: true
section4: true
section5: true
section6: true

# These variables correspond with the CIS rule IDs or paragraph numbers defined in
# the CIS benchmark documents.
# PLEASE NOTE: These work in coordination with the section # group variables and tags.
# You must enable an entire section in order for the variables below to take effect.
# Section 1 rules
rule_1_1_1_1: true
rule_1_1_1_2: true
rule_1_1_1_3: true
rule_1_1_1_4: true
rule_1_1_1_5: true
rule_1_1_1_6: true
rule_1_1_1_7: true
rule_1_1_1_8: true

# /tmp
rule_1_1_2_1_1: false
rule_1_1_2_1_2: false
rule_1_1_2_1_3: false
rule_1_1_2_1_4: false

# /dev/shm
rule_1_1_2_2_1: false
rule_1_1_2_2_2: false
rule_1_1_2_2_3: false
rule_1_1_2_2_4: false

# /home
rule_1_1_2_3_1: false
rule_1_1_2_3_2: false
rule_1_1_2_3_3: false

# /var
rule_1_1_2_4_1: false
rule_1_1_2_4_2: false
rule_1_1_2_4_3: false

# /var/tmp
rule_1_1_2_5_1: false
rule_1_1_2_5_2: false
rule_1_1_2_5_3: false
rule_1_1_2_5_4: false

# /var/log
rule_1_1_2_6_1: false
rule_1_1_2_6_2: false
rule_1_1_2_6_3: false
rule_1_1_2_6_4: false

# /var/log/audit
rule_1_1_2_7_1: false
rule_1_1_2_7_2: false
rule_1_1_2_7_3: false
rule_1_1_2_7_4: false

# DNF - Patching
rule_1_2_1: true
rule_1_2_2: true
rule_1_2_3: true
rule_1_2_4: true
rule_1_2_5: true

# bootloader grub
rule_1_3_1: false
rule_1_3_2: false

# kernel sysctl and coredumps
rule_1_4_1: false
rule_1_4_2: false
rule_1_4_3: false
rule_1_4_4: false

# SElinux
selinux_disable: true

# Crypto Policies
rule_1_6_1: true
rule_1_6_2: true
rule_1_6_3: true
rule_1_6_4: true

# MOTD and messages
rule_1_7_1: true
rule_1_7_2: true
rule_1_7_3: true
rule_1_7_4: true
rule_1_7_5: true
rule_1_7_6: true

# Gnome desktop
gui: false

# Section 2 rules
rule_2_1_1: true
rule_2_1_2: true
rule_2_2_1: true
rule_2_2_2: true
rule_2_2_3: true
rule_2_2_4: true
rule_2_2_5: true
rule_2_2_6: true
rule_2_2_7: true
rule_2_2_8: true
rule_2_2_9: true
rule_2_2_10: true
rule_2_2_11: true
rule_2_2_12: true
rule_2_2_13: true
rule_2_2_14: true
rule_2_2_15: true
rule_2_2_16: true
rule_2_2_17: true
rule_2_2_18: true
rule_2_2_19: true
rule_2_2_20: true
rule_2_3_1: true
rule_2_3_2: true
rule_2_3_3: true
rule_2_3_4: true
rule_2_3_5: true
rule_2_3_6: true
rule_2_4: true

# Section 3 rules
# network connectivity wifi/bluetooth/ipv6
rule_3_1_1: false
rule_3_1_2: false
rule_3_1_3: false

# Network Kernel module
rule_3_2_1: false
rule_3_2_2: false
rule_3_2_3: false
rule_3_2_4: false

# Network Kernel Params
rule_3_3_1: false
rule_3_3_2: false
rule_3_3_3: false
rule_3_3_4: false
rule_3_3_5: false
rule_3_3_6: false
rule_3_3_7: false
rule_3_3_8: false
rule_3_3_9: false
rule_3_3_10: false
rule_3_3_11: false

# Firewall
firewall: none

# Section 4 rules
# cron
rule_4_1_1_1: true
rule_4_1_1_2: true
rule_4_1_1_3: true
rule_4_1_1_4: true
rule_4_1_1_5: true
rule_4_1_1_6: true
rule_4_1_1_7: true
rule_4_1_1_8: true

# at
rule_4_1_2_1: true

# sshd
# Only if installed

# sudo
rule_4_3_1: false
rule_4_3_2: false
rule_4_3_3: false
rule_4_3_4: false
rule_4_3_5: false
rule_4_3_6: false
rule_4_3_7: false

# Pam software pkgs
rule_4_4_1_1: false
rule_4_4_1_2: false

# authselect
rule_4_4_2_1: false
rule_4_4_2_2: false
rule_4_4_2_3: false
rule_4_4_2_4: false
rule_4_4_2_5: false

# pam faillock
rule_4_4_3_1_1: false
rule_4_4_3_1_2: false
rule_4_4_3_1_3: false

# pam pwquality
rule_4_4_3_2_1: false
rule_4_4_3_2_2: false
rule_4_4_3_2_3: false
rule_4_4_3_2_4: false
rule_4_4_3_2_5: false
rule_4_4_3_2_6: false
rule_4_4_3_2_7: false

# pam pwhistory
rule_4_4_3_3_1: false
rule_4_4_3_3_2: false
rule_4_4_3_3_3: false

# pam pam_unix
rule_4_4_3_4_1: false
rule_4_4_3_4_2: false
rule_4_4_3_4_3: false
rule_4_4_3_4_4: false

# Shadow user settings
rule_4_5_1_1: true
rule_4_5_1_2: true
rule_4_5_1_3: true
rule_4_5_1_4: true
rule_4_5_1_5: true

# root and sys accts and env
rule_4_5_2_1: true
rule_4_5_2_2: true
rule_4_5_2_3: true
rule_4_5_2_4: true
rule_4_5_2_5: true

# User enviroment
rule_4_5_3_1: true
rule_4_5_3_2: true
rule_4_5_3_3: true

# Section 5 rules

syslog: none

# Rsyslog
rule_5_1_1_1: true
rule_5_1_1_2: true
rule_5_1_1_3: true
rule_5_1_1_4: true
rule_5_1_1_5: true
rule_5_1_1_6: true
rule_5_1_1_7: true

# Journald
rule_5_1_2_1_1: true
rule_5_1_2_1_2: true
rule_5_1_2_1_3: true
rule_5_1_2_1_4: true
rule_5_1_2_2: true
rule_5_1_2_3: true
rule_5_1_2_4: true
rule_5_1_2_5: true
rule_5_1_2_6: true
rule_5_1_3: true
rule_5_1_4: true

# Auditd
rule_5_2_1_1: true
rule_5_2_1_2: true
rule_5_2_1_3: true
rule_5_2_1_4: true
rule_5_2_2_1: true
rule_5_2_2_2: true
rule_5_2_2_3: true
rule_5_2_2_4: true

# auditd rules
rule_5_2_3_1: true
rule_5_2_3_2: true
rule_5_2_3_3: true
rule_5_2_3_4: true
rule_5_2_3_5: true
rule_5_2_3_6: true
rule_5_2_3_7: true
rule_5_2_3_8: true
rule_5_2_3_9: true
rule_5_2_3_10: true
rule_5_2_3_11: true
rule_5_2_3_12: true
rule_5_2_3_13: true
rule_5_2_3_14: true
rule_5_2_3_15: true
rule_5_2_3_16: true
rule_5_2_3_17: true
rule_5_2_3_18: true
rule_5_2_3_19: true
rule_5_2_3_20: true
rule_5_2_3_21: true

# auditd log perms
rule_5_2_4_1: true
rule_5_2_4_2: true
rule_5_2_4_3: true
rule_5_2_4_4: true
rule_5_2_4_5: true
rule_5_2_4_6: true
rule_5_2_4_7: true
rule_5_2_4_8: true
rule_5_2_4_9: true
rule_5_2_4_10: true

# AIDE

rule_5_3_1: true
rule_5_3_2: true
rule_5_3_3: true

# Section 6 rules
# System file perms
rule_6_1_1: true
rule_6_1_2: true
rule_6_1_3: true
rule_6_1_4: true
rule_6_1_5: true
rule_6_1_6: true
rule_6_1_7: true
rule_6_1_8: true
rule_6_1_9: true
rule_6_1_10: true
rule_6_1_11: true
rule_6_1_12: true
rule_6_1_13: true
rule_6_1_14: true

# local and usergroup
rule_6_2_1: true
rule_6_2_2: true
rule_6_2_3: true
rule_6_2_4: true
rule_6_2_5: true
rule_6_2_6: true
rule_6_2_7: true
rule_6_2_8: true
rule_6_2_9: true
rule_6_2_10: false
rule_6_2_11: true
