---

- name: "SECTION | 2.1 | Time Synchronization"
  ansible.builtin.import_tasks:
    file: 2.1.x.yml

- name: "SECTION | 2.2 | Special Purpose Services"
  ansible.builtin.import_tasks:
    file: 2.2.x.yml

- name: "SECTION | 2.3 | Service Clients"
  ansible.builtin.import_tasks:
    file: 2.3.x.yml
