---

galaxy_info:
  author: "iliyaag"
  description: "Apply the RHEL 8 CIS"
  company: "-"
  license: MIT
  role_name: rhel8
  namespace: ansible-lockdown
  min_ansible_version: 2.11.1
  platforms:
    - name: EL
      versions:
        - '8'
  galaxy_tags:
    - system
    - security
    - stig
    - hardening
    - benchmark
    - compliance
    - redhat
    - complianceascode
    - disa
    - rhel8
    - cis
    - rocky
    - alma
collections:
  - community.general
  - community.crypto
  - ansible.posix
dependencies: []
