---
# OS Specific Settings

os_gpg_key_pubkey_name: gpg-pubkey-c2a1e572-668fe8ef
os_gpg_key_pubkey_content: "AlmaLinux OS 10 <packager@almalinux.org> c2a1e572"
# disable repo_gpgcheck due to OS default repos
rule_enable_repogpg: false
