---
# vars file for rhel8
system_is_container: false

allowed_crypto_policies:
  - 'DEFAULT'
  - 'FUTURE'
  - 'FIPS'

# Following is left blank for ability to build string
crypto_policy_module: ''

# Do not adjust these are recognized as part of the CIS benchmark and used during testing
allowed_crypto_policies_modules:
  # Recognized by CIS as possible extra options
  - 'OSPP'
  - 'AD-SUPPORT'
  - 'AD-SUPPORT-LEGACY'
  # The following are already included in 1.6.x controls
  - 'NO-SHA1'
  - 'NO-SSHCBC'
  - 'NO-SSHETM'
  - 'NO-SSHWEAKCIPHER'
  - 'NO-SSHWEAKMAC'
  - 'NO-WEAKMAC'

# Used to control warning summary
warn_control_list: ""
warn_count: 0

# list of dicts of interactive users, filled in during prelim.yml
prelim_interactive_users: []

# Default empty values for 1.4.2
efi_mount_opts_addition: ''
