---

- name: "1.1.2.2.1 | PATCH | Ensure /dev/shm is a separate partition"
  when:
    - rule_1_1_2_2_1
    - required_mount not in prelim_mount_names
  tags:
    - level1-server
    - level1-workstation
    - audit
    - mounts
    - rule_1.1.2.2.1
    - NIST800-53R5_CM-7
  vars:
    warn_control_id: "1.1.2.2.1"
    required_mount: "/dev/shm"
  block:
    - name: "1.1.2.2.1 | AUDIT | Ensure /dev/shm is a separate partition | check for mount"
      ansible.builtin.command: findmnt -kn "{{ required_mount }}"
      changed_when: false
      failed_when: discovered_dev_shm_mount.rc not in [ 0, 1 ]
      register: discovered_dev_shm_mount

    - name: "1.1.2.2.1 | AUDIT | Ensure /dev/shm is a separate partition | Absent"
      when: discovered_dev_shm_mount is undefined
      ansible.builtin.debug:
        msg: "Warning!! {{ required_mount }} is not mounted on a separate partition"

    - name: "1.1.2.2.1 | AUDIT | Ensure /dev/shm is a separate partition | Present"
      when: discovered_dev_shm_mount is undefined
      ansible.builtin.import_tasks:
        file: warning_facts.yml
