---

# defaults file for rhel8-cis

system_is_container: false
# Place to find the container yml file for your environment - /vars/... This can be adjusted for your requirements.
container_vars_file: is_container.yml

os_check: true
# rhel8cis is left off the front of this var for consistency in testing pipeline
# system_is_ec2 toggle will disable tasks that fail on Amazon EC2 instances. Set true to skip and false to run tasks
system_is_ec2: false

section1: true
section2: true
section3: true
section4: true



level_1: true
level_2: true
selinux_disable: false

# Some tests can have a heavy impact on system e.g. find on all filesystems etc
disruption_high: false

## Python Binary
## This is used for python3 Installations where python2 OS modules are used in ansible
python2_bin: /bin/python2.7

# Create managed not custom local_facts files
create_benchmark_facts: true
ansible_facts_path: /etc/ansible/facts.d

## Benchmark name used by auditing control role
# The audit variable found at the base
benchmark: RHEL8-CIS
benchmark_version: v3.0.0

# Whether to skip the reboot
skip_reboot: true

# default value will change to true but wont reboot if not enabled but will error
change_requires_reboot: false

# Modify behavior of changed_when if reboot is pending and skipped to allow idempotency to succeed
reboot_warning_changed_when: true

###
### Settings for associated Audit role using Goss
###

###########################################
### Goss is required on the remote host ###
### vars/auditd.yml for other settings  ###

# Allow audit to setup the requirements including installing git (if option chosen and downloading and adding goss binary to system)
setup_audit: false

# enable audits to run - this runs the audit and get the latest content
run_audit: false
# Run heavy tests - some tests can have more impact on a system enabling these can have greater impact on a system
audit_run_heavy_tests: true
# Ability to limit the number of concurrent processes used by goss (default 50)
audit_max_concurrent: 50

## Only run Audit do not remediate
audit_only: false

### As part of audit_only ###
# Path to copy the files to will create dir structure in audit_only mode
audit_capture_files_dir: /some/location to copy to on control node
#############################

# How to retrieve audit binary
# Options are copy or download - detailed settings at the bottom of this file
# you will need to access to either github or the file already downloaded
get_audit_binary_method: download

## if get_audit_binary_method - copy the following needs to be updated for your environment
## it is expected that it will be copied from somewhere accessible to the control node
## e.g copy from ansible control node to remote host
audit_bin_copy_location: /some/accessible/path

# how to get audit files onto host options
# options are git/copy/archive/get_url other e.g. if you wish to run from already downloaded conf
audit_content: git

# If using either archive, copy, get_url:
## Note will work with .tar files - zip will require extra configuration
### If using get_url this is expecting github url in tar.gz format e.g.
### https://github.com/ansible-lockdown/RHEL8-CIS-Audit/archive/refs/heads/benchmark-v1.0.0.tar.gz
audit_conf_source: "some path or url to copy from"

# Destination for the audit content to be placed on managed node
# note may not need full path e.g. /opt with the directory being the {{ benchmark }}-Audit directory
audit_conf_dest: "/opt"

# Where the audit logs are stored
audit_log_dir: '/opt'

## Ability to collect and take audit files moving to a centralized location
# This enables the collection of the files from the host
fetch_audit_output: false

# Method of getting,uploading the summary files
## Ensure access and permissions are available for these to occur.
## options are
# fetch - fetches from server and moves to location on the ansible controller (could be a mount point available to controller)
# copy - copies file to a location available to the managed node
audit_output_collection_method: fetch

# Location to put the audit files
audit_output_destination: /opt/audit_summaries/

### Goss Settings ##
####### END ########

# These variables correspond with the CIS rule IDs or paragraph numbers defined in
# the CIS benchmark documents.
# PLEASE NOTE: These work in coordination with the section # group variables and tags.
# You must enable an entire section in order for the variables below to take effect.
# Section 1 rules
rule_1_1_1_1: true
rule_1_1_1_2: true
rule_1_1_1_3: true
rule_1_1_1_4: true
rule_1_1_1_5: true
rule_1_1_1_6: true
rule_1_1_1_7: true
rule_1_1_1_8: true

# /tmp
rule_1_1_2_1_1: true
rule_1_1_2_1_2: true
rule_1_1_2_1_3: true
rule_1_1_2_1_4: true

# /dev/shm
rule_1_1_2_2_1: true
rule_1_1_2_2_2: true
rule_1_1_2_2_3: true
rule_1_1_2_2_4: true

# /home
rule_1_1_2_3_1: true
rule_1_1_2_3_2: true
rule_1_1_2_3_3: true

# /var
rule_1_1_2_4_1: true
rule_1_1_2_4_2: true
rule_1_1_2_4_3: true

# /var/tmp
rule_1_1_2_5_1: true
rule_1_1_2_5_2: true
rule_1_1_2_5_3: true
rule_1_1_2_5_4: true

# /var/log
rule_1_1_2_6_1: true
rule_1_1_2_6_2: true
rule_1_1_2_6_3: true
rule_1_1_2_6_4: true

# /var/log/audit
rule_1_1_2_7_1: true
rule_1_1_2_7_2: true
rule_1_1_2_7_3: true
rule_1_1_2_7_4: true

# DNF - Patching
rule_1_2_1: true
rule_1_2_2: true
rule_1_2_3: true
rule_1_2_4: true
rule_1_2_5: true

# bootloader grub
rule_1_3_1: true
rule_1_3_2: true

# kernel sysctl and coredumps
rule_1_4_1: true
rule_1_4_2: true
rule_1_4_3: true
rule_1_4_4: true

# SElinux
rule_1_5_1_1: true
rule_1_5_1_2: true
rule_1_5_1_3: true
rule_1_5_1_4: true
rule_1_5_1_5: true
rule_1_5_1_6: true
rule_1_5_1_7: true
rule_1_5_1_8: true

# Crypto Policies
rule_1_6_1: true
rule_1_6_2: true
rule_1_6_3: true
rule_1_6_4: true

# MOTD and messages
rule_1_7_1: true
rule_1_7_2: true
rule_1_7_3: true
rule_1_7_4: true
rule_1_7_5: true
rule_1_7_6: true

# Gnome desktop
rule_1_8_1: true
rule_1_8_2: true
rule_1_8_3: true
rule_1_8_4: true
rule_1_8_5: true
rule_1_8_6: true
rule_1_8_7: true
rule_1_8_8: true
rule_1_8_9: true
rule_1_8_10: true

# Section 2 rules
# time sync
rule_2_1_1: true
rule_2_1_2: true
rule_2_1_3: true

# Server services
rule_2_2_1: true
rule_2_2_2: true
rule_2_2_3: true
rule_2_2_4: true
rule_2_2_5: true
rule_2_2_6: true
rule_2_2_7: true
rule_2_2_8: true
rule_2_2_9: true
rule_2_2_10: true
rule_2_2_11: true
rule_2_2_12: true
rule_2_2_13: true
rule_2_2_14: true
rule_2_2_15: true
rule_2_2_16: true
rule_2_2_17: true
rule_2_2_18: true
rule_2_2_19: true
rule_2_2_20: true
rule_2_2_21: true
rule_2_2_22: true

# Client services
rule_2_3_1: true
rule_2_3_2: true
rule_2_3_3: true
rule_2_3_4: true
rule_2_3_5: true

# Section 3 rules
# network connectivity wifi/bluetooth/ipv6
rule_3_1_1: true
rule_3_1_2: true
rule_3_1_3: true

# Network Kernel module
rule_3_2_1: true
rule_3_2_2: true
rule_3_2_3: true
rule_3_2_4: true

# Network Kernel Params
rule_3_3_1: true
rule_3_3_2: true
rule_3_3_3: true
rule_3_3_4: true
rule_3_3_5: true
rule_3_3_6: true
rule_3_3_7: true
rule_3_3_8: true
rule_3_3_9: true
rule_3_3_10: true
rule_3_3_11: true

# Firewall
rule_3_4_1_1: true
rule_3_4_1_2: true

# Firewall rules
rule_3_4_2_1: true
rule_3_4_2_2: true
rule_3_4_2_3: true
rule_3_4_2_4: true
rule_3_4_2_5: true

##
## Section 4 rules
##
# cron
rule_4_1_1_1: true
rule_4_1_1_2: true
rule_4_1_1_3: true
rule_4_1_1_4: true
rule_4_1_1_5: true
rule_4_1_1_6: true
rule_4_1_1_7: true
rule_4_1_1_8: true

# at
rule_4_1_2_1: true

# sshd
rule_4_2_1: true
rule_4_2_2: true
rule_4_2_3: true
rule_4_2_4: true
rule_4_2_5: true
rule_4_2_6: true
rule_4_2_7: true
rule_4_2_8: true
rule_4_2_9: true
rule_4_2_10: true
rule_4_2_12: true
rule_4_2_11: true
rule_4_2_13: true
rule_4_2_14: true
rule_4_2_15: true
rule_4_2_16: true
rule_4_2_17: true
rule_4_2_18: true
rule_4_2_19: true
rule_4_2_20: true
rule_4_2_21: true
rule_4_2_22: true

# sudo
rule_4_3_1: true
rule_4_3_2: true
rule_4_3_3: true
rule_4_3_4: true
rule_4_3_5: true
rule_4_3_6: true
rule_4_3_7: true

# Pam software pkgs
rule_4_4_1_1: true
rule_4_4_1_2: true

# authselect
rule_4_4_2_1: true
rule_4_4_2_2: true
rule_4_4_2_3: true
rule_4_4_2_4: true
rule_4_4_2_5: true

# pam faillock
rule_4_4_3_1_1: true
rule_4_4_3_1_2: true
rule_4_4_3_1_3: true

# pam pwquality
rule_4_4_3_2_1: true
rule_4_4_3_2_2: true
rule_4_4_3_2_3: true
rule_4_4_3_2_4: true
rule_4_4_3_2_5: true
rule_4_4_3_2_6: true
rule_4_4_3_2_7: true

# pam pwhistory
rule_4_4_3_3_1: true
rule_4_4_3_3_2: true
rule_4_4_3_3_3: true

# pam pam_unix
rule_4_4_3_4_1: true
rule_4_4_3_4_2: true
rule_4_4_3_4_3: true
rule_4_4_3_4_4: true

# Shadow user settings
rule_4_5_1_1: true
rule_4_5_1_2: true
rule_4_5_1_3: true
rule_4_5_1_4: true
rule_4_5_1_5: true

# root and sys accts and env
rule_4_5_2_1: true
rule_4_5_2_2: true
rule_4_5_2_3: true
rule_4_5_2_4: true
rule_4_5_2_5: true

# User environment
rule_4_5_3_1: true
rule_4_5_3_2: true
rule_4_5_3_3: true
##
## Section 1 vars
##
# 1.1.2.2
# 1.1.2.3
# 1.1.2.4
# These settings go into the /etc/fstab file for the /tmp mount settings
# The value must contain nosuid,nodev,noexec to conform to CIS standards
# tmp_tmpfs_settings: "defaults,rw,nosuid,nodev,noexec,relatime 0 0"
# If set true uses the tmp.mount service else using fstab configuration
tmp_svc: false

# 1.2 patch system
apply_installed_kernel_limit: false
installed_kernel_limit: 2

# 1.3 Bootloader password
bootloader_password_hash: 'grub.pbkdf2.sha512.changethispassword'  # pragma: allowlist secret
bootloader_password: random  # pragma: allowlist secret
set_boot_pass: false

# 1.5 SELinux policy
selinux_state: enforcing
# Configure SELinux to meet or exceed the default targeted policy, which constrains daemons and system software only.
# Valid Inputs: targeted or mls
selinux_policy: targeted

## Control 1.6
# This variable contains the value to be set as the system-wide crypto policy. Current rule enforces NOT USING
# 'LEGACY' value(as it is less secure, it just ensures compatibility with legacy systems), therefore
# possible values for this variable are, as explained by RedHat docs:
#  -'DEFAULT': reasonable default policy for today's standards (balances usability and security)
#  -'FUTURE': conservative security level that is believed to withstand any near-term future attacks
#  -'FIPS': A level that conforms to the FIPS140-2 requirements
crypto_policy: 'DEFAULT'

## Control 1.6
# This variable contains the value of the crypto policy module(combinations of policies and
# sub-policies) to be allowed as default setting. Allowed options are defined in 'vars/main.yml' file,
# using those listed in the 'rhel9cis_allowed_crypto_policies_modules' variable.
additional_crypto_policy_module: ''

# 1.7
# Warning Banner Content (issue, issue.net, motd)
warning_banner: |
    Authorized users only. All activity may be monitored and reported.
# End Banner

# 1.8 Gnome Desktop
# Whether or not to run tasks related to auditing/patching the desktop environment
gui: false
dconf_db_name: local
screensaver_idle_delay: 900  # Set max value for idle-delay in seconds (between 1 and 900)
screensaver_lock_delay: 5  # Set max value for lock-delay in seconds (between 0 and 5)
##
## Section 2 vars
##
# 2.1.1 Time Synchronization - Either chrony or ntp
time_synchronization: chrony

# Time Synchronization servers - used in template file chrony.conf.j2
time_synchronization_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

chrony_server_options: "minpoll 8"
ntp_server_options: "iburst"

# Service configuration
# Options are
# true to leave installed if exists not changes take place
# false - this removes the package
# mask - if a dependency for product so cannot be removed
# Server Services
autofs_services: false
autofs_mask: false
avahi_server: false
avahi_mask: false
dhcp_server: false
dhcp_mask: false
dns_server: false
dns_mask: false
dnsmasq_server: false
dnsmasq_mask: false
samba_server: false
samba_mask: false
ftp_server: false
ftp_mask: false
message_server: false  # This is for messaging dovecot and cyrus-imap
message_mask: false
nfs_server: true
nfs_mask: true
nis_server: true  # set to mask if nis client required
nis_mask: false
print_server: false  # replaces cups
print_mask: false
rpc_server: true
rpc_mask: true
rsync_server: false
rsync_mask: false
net_snmp_server: false
net_snmp_mask: false
telnet_server: false
telnet_mask: false
tftp_server: false
tftp_mask: false
squid_server: false
squid_mask: false
httpd_server: false
httpd_mask: false
nginx_server: false
nginx_mask: false
xinetd_server: false
xinetd_mask: false
xwindow_server: false  # will remove mask not an option
is_mail_server: false

# Client Services
ftp_client: false
openldap_clients_required: false
ypbind_required: false  # Same package as NIS server
telnet_required: false
tftp_client: false

##
## Section 3 vars
##

bluetooth_service: false
bluetooth_mask: false

# System network parameters (host only OR host and router)
is_router: false

# IPv6 required
ipv6_required: true

ipv6_sysctl_force: true

##  Optional - Understand the impact of making the following two control to true
# By default, we do not disable IPv6 on localhost, as it's important for multiple
# components.  If you want to disable it anyway, change the following
# value to true refer https://access.redhat.com/solutions/8709
# this changes sysctl and /etc/hosts
# requires reboot
ipv6_disable_localhost: false
# disable ipv6 for sshd
ipv6_sshd_disable: false
# disable chrony on ipv6
ipv6_chrony_disable: false

# Set to 'true' if X Windows is needed in your environment
xwindows_required: false

## Section3 vars

# default location for the sysctl overrides.
sysctl_file: /etc/sysctl.d/99_cis.conf

# Firewall Service - either firewalld or nftables
firewall: 'firewalld'

default_zone: public

nft_tables_autonewtable: true
nft_tables_tablename: filter

# 3.4.2.6 Set nftables new chain create
nft_tables_autochaincreate: true

#######
## Section5 vars
######

# This value, containing the absolute filepath of the produced 'sshd' config file, allows usage of
# drop-in files('/etc/ssh/ssh_config.d/{ssh_drop_in_name}.conf', supported by RHEL>=8.6) when CIS adopts them.
# Otherwise, the default value is '/etc/ssh/ssh_config'.
sshd_config_file: /etc/ssh/sshd_config

## If using the allow/deny user groups options
sshd_limited: false
sshd_clientalivecountmax: 3
sshd_clientaliveinterval: 15
sshd_logingracetime: 60
sshd_loglevel: INFO
sshd_macs: '-hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-sha1-96,umac-64@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,umac-64-etm@openssh.com'
sshd_maxauthtries: 4
sshd_maxsessions: 10
sshd_maxstartups: "10:30:60"
sshd_ciphers: '-3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se'
sshd_kex: '-diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1'
# WARNING: make sure you understand the precedence when working with these values!!
## Only runs if value sshd_limited is true
# sshd_allowusers:
# sshd_allowgroups: systems dba
# sshd_denyusers:
# sshd_denygroups:

# 4.3. sudo
sudolog_location: "/var/log/sudo.log"
sudo_timestamp_timeout: 15

## PAM
## 4.4.2.x PAM and Authselect
# Do not use authselect if:
# Your host is part of Linux Identity Management.
# Joining your host to an IdM domain with the ipa-client-install command automatically configures SSSD authentication on your host.
# Your host is part of Active Directory via SSSD.
# Calling the realm join command to join your host to an Active Directory domain automatically configures SSSD authentication on your host.
allow_authselect_updates: true
##
authselect_pkg_update: false  # NOTE the risks if system is using SSSD or using ipa-client-install

## PAM AND Authselect

# To create a new profile (best for greenfield fresh sites not configured)
# This allows creation of a custom profile using an existing one to build from
# will only create if profile does not already exist
## options true or false
authselect_custom_profile_create: true
## Controls:
#  - 4.4.2.1 - Ensure custom authselect profile is used
# Settings in place now will fail, they are placeholders from the control example. Due to the way many multiple
# options and ways to configure this control needs to be enabled and settings adjusted to minimize risk.

# This variable configures the name of the custom profile to be created and selected.
# To be changed from default - cis_example_profile
authselect_custom_profile_name: cis_example_profile
# Name of the existing authselect profile to copy - options can be found with
# ```authselect list``` on the host to be configured
authselect_default_profile_to_copy: "sssd --symlink-meta"

pam_faillock_attempts: 5
pam_faillock_deny: 5
pam_faillock_interval: 900
pam_faillock_unlock_time: 900
pam_faillock_root_unlock_time: 60
# Choose options below for root options
pam_faillock_root_option: even_deny_root
# root_option: "root_unlock_time = {{ root_unlock_time }}"

pam_pwquality_difok: 2
pam_pwquality_maxrepeat: 3
pam_pwquality_maxseq: 3
pam_pwquality_minlen: 14
pam_pwquality_minclass: 4

pam_pwhistory_remember: 24

pam_pwhash: sha512

pam_pass_inactive: 30
pam_pass_max_days: 365  # Max 365
pam_pass_min_days: 7
pam_pass_warn_age: 7

## Control 4.5.2.3 - Ensure system accounts are secured | Set nologin
# The system users on this list are allowed to have a shell (e.g. applications
# that require a shell to function)
system_users_shell: []

## Set the following to true if you wish to adjust accounts greater than pass['max_days']
set_max_expiry: false

## Add users to be skipped if required
user_skip_list:
  root

root_umask: '0027'  # 0027 or more restrictive

shell_session_file: /etc/profile.d/tmout.sh
shell_session_timeout: 900

# sugroup
sugroup: sugroup

# wheel users list
sugroup_users: "root"

# Its not provider recommended to run changes to pam files manually that affects authentication
# This control needs to be set to ACCEPT this so that the changes do take place
# Any other value does nothing
pamd_manual_risks: NEVER

inactivelock:
  lock_days: 30

# Allow ansible to expire password for account with a last changed date in the future. False will just display users in violation, true will expire those users passwords
futurepwchgdate_autofix: true
